
services:
  postgres:
    image: postgres:16-alpine
    container_name: ocpp-postgres
    environment:
      POSTGRES_USER: ocpp_user
      POSTGRES_PASSWORD: ocpp_password
      POSTGRES_DB: ocpp_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ocpp_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ocpp-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ocpp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres
    networks:
      - ocpp-network

volumes:
  postgres_data:

networks:
  ocpp-network:
    driver: bridge
